# Auto generate data to test terminal ui
fake_data: false

# GeoLite DB path
geolite:
  asn: data/geolite2/GeoLite2-ASN_20210706/GeoLite2-ASN.mmdb
  city: data/geolite2/GeoLite2-City_20210706/GeoLite2-City.mmdb
  country: data/geolite2/GeoLite2-Country_20210706/GeoLite2-Country.mmdb

# Block address
blocked_address: "172.31.7.37"